import type { Car, CategoryMeta } from "@/types/car";

// Inventory sourced directly from the Makmur Motor Google Drive spec sheets.
// Harga = harga kredit (harga yang diiklankan); hargaCash = harga cash.
export const cars: Car[] = [
  {
    id: "agya-g-trd-2018",
    nama: "Toyota Agya G TRD",
    tahun: 2018,
    harga: 115000000,
    hargaFormatted: "Rp 115.000.000",
    hargaCash: 120000000,
    hargaCashFormatted: "Rp 120.000.000",
    kategori: "Hatchback",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "65.000",
    warna: "Merah",
    lokasi: "Showroom Antasura",
    folderFoto: "agya-g-trd-2018",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Toyota Agya G TRD 2018",
    featured: false,
  },
  {
    id: "avanza-g-2020",
    nama: "Toyota Avanza G",
    tahun: 2020,
    harga: 175000000,
    hargaFormatted: "Rp 175.000.000",
    hargaCash: 180000000,
    hargaCashFormatted: "Rp 180.000.000",
    kategori: "MPV",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "95.000",
    warna: "Hitam",
    lokasi: "Showroom Antasura",
    folderFoto: "avanza-g-2020",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Toyota Avanza G 2020",
    featured: false,
  },
  {
    id: "brv-e-2022",
    nama: "Honda BR-V E",
    tahun: 2022,
    harga: 200000000,
    hargaFormatted: "Rp 200.000.000",
    hargaCash: 205000000,
    hargaCashFormatted: "Rp 205.000.000",
    kategori: "SUV",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "51.000",
    warna: "Putih",
    lokasi: "Showroom Antasura",
    folderFoto: "brv-e-2022",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Honda BR-V E 2022",
    featured: true,
  },
  {
    id: "engkel-box-2013",
    nama: "Engkel Box",
    tahun: 2013,
    harga: 233000000,
    hargaFormatted: "Rp 233.000.000",
    hargaCash: 235000000,
    hargaCashFormatted: "Rp 235.000.000",
    kategori: "Commercial",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "15.000",
    warna: "Putih",
    lokasi: "Showroom Antasura",
    folderFoto: "engkel-box-2013",
    whatsappMessage: "Halo Makmur Motor, saya tertarik dengan Engkel Box 2013",
    featured: false,
  },
  {
    id: "engkel-box-2016",
    nama: "Engkel Box",
    tahun: 2016,
    harga: 245000000,
    hargaFormatted: "Rp 245.000.000",
    hargaCash: 250000000,
    hargaCashFormatted: "Rp 250.000.000",
    kategori: "Commercial",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "107.000",
    lokasi: "Showroom Antasura",
    folderFoto: "engkel-box-2016",
    whatsappMessage: "Halo Makmur Motor, saya tertarik dengan Engkel Box 2016",
    featured: false,
  },
  {
    id: "canter-engkel-2015",
    nama: "Mitsubishi Canter Engkel",
    tahun: 2015,
    harga: 248000000,
    hargaFormatted: "Rp 248.000.000",
    hargaCash: 250000000,
    hargaCashFormatted: "Rp 250.000.000",
    kategori: "Commercial",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "155.000",
    warna: "Kuning",
    lokasi: "Showroom Antasura",
    folderFoto: "canter-engkel-2015",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Mitsubishi Canter Engkel 2015",
    featured: false,
  },
  {
    id: "hrv-e-cvt-2018",
    nama: "Honda HR-V E CVT",
    tahun: 2018,
    harga: 255000000,
    hargaFormatted: "Rp 255.000.000",
    hargaCash: 260000000,
    hargaCashFormatted: "Rp 260.000.000",
    kategori: "SUV",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "—",
    lokasi: "Showroom Antasura",
    folderFoto: "hrv-e-cvt-2018",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Honda HR-V E CVT 2018",
    featured: true,
  },
  {
    id: "innova-reborn-diesel-2021",
    nama: "Toyota Innova Reborn Diesel",
    tahun: 2021,
    harga: 345000000,
    hargaFormatted: "Rp 345.000.000",
    hargaCash: 350000000,
    hargaCashFormatted: "Rp 350.000.000",
    kategori: "MPV",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "33.000",
    warna: "Putih",
    lokasi: "Showroom Antasura",
    folderFoto: "innova-reborn-diesel-2021",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Toyota Innova Reborn Diesel 2021",
    featured: true,
  },
  {
    id: "new-carry-acps-2024",
    nama: "Suzuki New Carry AC PS",
    tahun: 2024,
    harga: 143000000,
    hargaFormatted: "Rp 143.000.000",
    hargaCash: 145000000,
    hargaCashFormatted: "Rp 145.000.000",
    kategori: "Pickup",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "18.000",
    lokasi: "Showroom Antasura",
    folderFoto: "new-carry-acps-2024",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Suzuki New Carry AC PS 2024",
    featured: false,
  },
  {
    id: "new-carry-std-2023",
    nama: "Suzuki New Carry STD",
    tahun: 2023,
    harga: 123000000,
    hargaFormatted: "Rp 123.000.000",
    hargaCash: 125000000,
    hargaCashFormatted: "Rp 125.000.000",
    kategori: "Pickup",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "56.000",
    warna: "Hitam",
    lokasi: "Showroom Antasura",
    folderFoto: "new-carry-std-2023",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Suzuki New Carry STD 2023",
    featured: false,
  },
  {
    id: "pajero-sport-dakar-2023",
    nama: "Mitsubishi Pajero Sport Dakar",
    tahun: 2023,
    harga: 525000000,
    hargaFormatted: "Rp 525.000.000",
    kategori: "SUV",
    transmisi: "Matic",
    bahanBakar: "Diesel",
    km: "10.000",
    warna: "Hitam",
    lokasi: "Showroom Antasura",
    folderFoto: "pajero-sport-dakar-2023",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Mitsubishi Pajero Sport Dakar 2023",
    featured: true,
  },
  {
    id: "panther-pickup-acps-2017",
    nama: "Isuzu Panther Pick Up AC PS",
    tahun: 2017,
    harga: 146000000,
    hargaFormatted: "Rp 146.000.000",
    hargaCash: 148000000,
    hargaCashFormatted: "Rp 148.000.000",
    kategori: "Pickup",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "—",
    lokasi: "Showroom Antasura",
    folderFoto: "panther-pickup-acps-2017",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Isuzu Panther Pick Up AC PS 2017",
    featured: false,
  },
  {
    id: "panther-pickup-2014",
    nama: "Isuzu Panther Pickup",
    tahun: 2014,
    harga: 131000000,
    hargaFormatted: "Rp 131.000.000",
    hargaCash: 133000000,
    hargaCashFormatted: "Rp 133.000.000",
    kategori: "Pickup",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "148.000",
    warna: "Putih",
    lokasi: "Showroom Antasura",
    folderFoto: "panther-pickup-2014",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Isuzu Panther Pickup 2014",
    featured: false,
  },
  {
    id: "rush-gr-sport-2021",
    nama: "Toyota Rush GR Sport",
    tahun: 2021,
    harga: 240000000,
    hargaFormatted: "Rp 240.000.000",
    hargaCash: 245000000,
    hargaCashFormatted: "Rp 245.000.000",
    kategori: "SUV",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "62.000",
    warna: "Hitam",
    lokasi: "Showroom Antasura",
    folderFoto: "rush-gr-sport-2021",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Toyota Rush GR Sport 2021",
    featured: true,
  },
  {
    id: "sienta-v-2017",
    nama: "Toyota Sienta V",
    tahun: 2017,
    harga: 145000000,
    hargaFormatted: "Rp 145.000.000",
    hargaCash: 150000000,
    hargaCashFormatted: "Rp 150.000.000",
    kategori: "MPV",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "32.000",
    warna: "Oren",
    lokasi: "Showroom Antasura",
    folderFoto: "sienta-v-2017",
    whatsappMessage: "Halo Makmur Motor, saya tertarik dengan Toyota Sienta V 2017",
    featured: false,
  },
  {
    id: "ertiga-gl-2023",
    nama: "Suzuki Ertiga GL",
    tahun: 2023,
    harga: 190000000,
    hargaFormatted: "Rp 190.000.000",
    hargaCash: 195000000,
    hargaCashFormatted: "Rp 195.000.000",
    kategori: "MPV",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "53.000",
    lokasi: "Showroom Antasura",
    folderFoto: "ertiga-gl-2023",
    whatsappMessage: "Halo Makmur Motor, saya tertarik dengan Suzuki Ertiga GL 2023",
    featured: true,
  },
  {
    id: "futura-2014",
    nama: "Suzuki Futura",
    tahun: 2014,
    harga: 98000000,
    hargaFormatted: "Rp 98.000.000",
    hargaCash: 100000000,
    hargaCashFormatted: "Rp 100.000.000",
    kategori: "Pickup",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "79.000",
    warna: "Putih",
    lokasi: "Showroom Antasura",
    folderFoto: "futura-2014",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Suzuki Futura 2014",
    featured: false,
  },
  {
    id: "traga-box-2023",
    nama: "Isuzu Traga Box",
    tahun: 2023,
    harga: 233000000,
    hargaFormatted: "Rp 233.000.000",
    hargaCash: 235000000,
    hargaCashFormatted: "Rp 235.000.000",
    kategori: "Commercial",
    transmisi: "Manual",
    bahanBakar: "Diesel",
    km: "40.000",
    warna: "Putih",
    lokasi: "Showroom Antasura",
    folderFoto: "traga-box-2023",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Isuzu Traga Box 2023",
    featured: false,
  },
  {
    id: "confero-2021",
    nama: "Wuling Confero",
    tahun: 2021,
    harga: 95000000,
    hargaFormatted: "Rp 95.000.000",
    hargaCash: 100000000,
    hargaCashFormatted: "Rp 100.000.000",
    kategori: "MPV",
    transmisi: "Manual",
    bahanBakar: "Bensin",
    km: "17.000",
    warna: "Silver",
    lokasi: "Showroom Antasura",
    folderFoto: "confero-2021",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Wuling Confero 2021",
    featured: false,
  },
  {
    id: "xenia-ads-2022",
    nama: "Daihatsu Xenia 1.3 ADS",
    tahun: 2022,
    harga: 195000000,
    hargaFormatted: "Rp 195.000.000",
    hargaCash: 200000000,
    hargaCashFormatted: "Rp 200.000.000",
    kategori: "MPV",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "65.000",
    warna: "Hitam",
    lokasi: "Showroom Antasura",
    folderFoto: "xenia-ads-2022",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Daihatsu Xenia 1.3 ADS 2022",
    featured: false,
  },
  {
    id: "xl7-zeta-2024",
    nama: "Suzuki XL7 Zeta",
    tahun: 2024,
    harga: 215000000,
    hargaFormatted: "Rp 215.000.000",
    hargaCash: 220000000,
    hargaCashFormatted: "Rp 220.000.000",
    kategori: "SUV",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "15.500",
    lokasi: "Showroom Antasura",
    folderFoto: "xl7-zeta-2024",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Suzuki XL7 Zeta 2024",
    featured: true,
  },
  {
    id: "xpander-sport-2019",
    nama: "Mitsubishi Xpander Sport",
    tahun: 2019,
    harga: 205000000,
    hargaFormatted: "Rp 205.000.000",
    hargaCash: 210000000,
    hargaCashFormatted: "Rp 210.000.000",
    kategori: "MPV",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "69.000",
    warna: "Silver",
    lokasi: "Showroom Antasura",
    folderFoto: "xpander-sport-2019",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Mitsubishi Xpander Sport 2019",
    featured: true,
  },
  {
    id: "yaris-trd-sportivo-2019",
    nama: "Toyota Yaris TRD Sportivo",
    tahun: 2019,
    harga: 210000000,
    hargaFormatted: "Rp 210.000.000",
    hargaCash: 215000000,
    hargaCashFormatted: "Rp 215.000.000",
    kategori: "Hatchback",
    transmisi: "Matic",
    bahanBakar: "Bensin",
    km: "—",
    warna: "Hitam",
    lokasi: "Showroom Antasura",
    folderFoto: "yaris-trd-sportivo-2019",
    whatsappMessage:
      "Halo Makmur Motor, saya tertarik dengan Toyota Yaris TRD Sportivo 2019",
    featured: true,
  },
];

export const categories: CategoryMeta[] = [
  {
    key: "SUV",
    label: "SUV",
    description: "Tangguh & nyaman untuk segala medan",
    gradient: "from-blue-600 via-blue-700 to-slate-900",
  },
  {
    key: "MPV",
    label: "MPV",
    description: "Lapang untuk keluarga besar",
    gradient: "from-indigo-600 via-indigo-700 to-slate-900",
  },
  {
    key: "Commercial",
    label: "Commercial",
    description: "Andalan bisnis & niaga Anda",
    gradient: "from-slate-700 via-slate-800 to-slate-900",
  },
  {
    key: "Pickup",
    label: "Pickup",
    description: "Kuat angkut, irit bahan bakar",
    gradient: "from-zinc-700 via-zinc-800 to-slate-900",
  },
];

// Reference uses clean white cards with a thin border — no color tints.
export const cardTints = ["bg-white", "bg-white", "bg-white", "bg-white"];

export function getCarById(id: string): Car | undefined {
  return cars.find((c) => c.id === id);
}

export function getFeaturedCars(): Car[] {
  return cars.filter((c) => c.featured);
}

export function getRelatedCars(car: Car, limit = 4): Car[] {
  return cars
    .filter((c) => c.kategori === car.kategori && c.id !== car.id)
    .slice(0, limit);
}

export function getCountByCategory(key: string): number {
  return cars.filter((c) => c.kategori === key).length;
}

export const allCategories = [
  "SUV",
  "MPV",
  "Commercial",
  "Pickup",
  "Hatchback",
] as const;

export const allTransmisi = ["Manual", "Matic"] as const;

export const allLokasi = ["Showroom Antasura"] as const;
