// Generates drizzle/seed.sql from the original static inventory (lib/data.ts)
// plus the photos found in public/cars/<folder>. Run with `npm run db:seed`.
// Apply locally/remotely with `db:seed:local` / `db:seed:remote`.
//
// Runs on plain Node (TypeScript is stripped natively). It re-implements the
// folder photo scan here so it doesn't need to import lib/photos.ts (which uses
// the "@/..." path alias that Node can't resolve).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { cars } from "../lib/data.ts";
import { THUMBNAILS } from "../lib/thumbnails.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

function scanPhotos(folder: string): string[] {
  const dir = path.join(ROOT, "public", "cars", folder);
  let files: string[];
  try {
    files = fs
      .readdirSync(dir)
      .filter((f) => /\.(jpe?g|png|webp|avif)$/i.test(f))
      .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  } catch {
    return [];
  }
  const thumb = THUMBNAILS[folder];
  if (thumb && files.includes(thumb)) {
    files = [thumb, ...files.filter((f) => f !== thumb)];
  }
  return files.map((f) => `/cars/${folder}/${f}`);
}

function sql(value: string | number | null): string {
  if (value === null) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

// index 0 gets the largest createdAt so the original array order is preserved
// when the app sorts by createdAt DESC. Base is a fixed past timestamp so any
// admin-added car (createdAt = now) sorts ahead of the seeded inventory.
const SEED_BASE = 1_700_000_000_000;

const lines: string[] = [
  "-- Seed data generated by scripts/build-seed.ts. Do not edit by hand.",
  "DELETE FROM cars;",
];

cars.forEach((car, i) => {
  const photos = scanPhotos(car.folderFoto);
  const ts = SEED_BASE - i * 1000;
  const values = [
    sql(car.id),
    sql(car.nama),
    sql(car.tahun),
    sql(car.harga),
    sql(car.hargaCash ?? null),
    sql(car.kategori),
    sql(car.transmisi),
    sql(car.bahanBakar),
    sql(car.km),
    sql(car.warna ?? null),
    sql(car.lokasi),
    sql(car.folderFoto),
    sql(car.whatsappMessage),
    sql(car.featured ? 1 : 0),
    sql(0), // sold
    sql(JSON.stringify(photos)),
    sql(ts),
    sql(ts),
  ].join(", ");
  lines.push(
    "INSERT INTO cars (id, nama, tahun, harga, harga_cash, kategori, transmisi, bahan_bakar, km, warna, lokasi, folder_foto, whatsapp_message, featured, sold, photos, created_at, updated_at) VALUES (" +
      values +
      ");",
  );
});

const out = path.join(ROOT, "scripts", "seed.sql");
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${out} (${cars.length} cars).`);
